# A simple way to display matrices using LaTex/MathJax

* [https://www.mathjax.org/](https://www.mathjax.org/)
* [MathJax Latex Syntax](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference)

In [1]:
#!pip -q install --user watermark tensorflow numpy pytorch

In [2]:
from IPython.display import Math
from IPython.display import Markdown
import tensorflow as tf
import torch
import numpy as np

def to_list(inmat):
    mat = inmat
    # Pythonify the TensorFlow
    if isinstance(inmat,tf.Variable):
        mat = inmat.numpy().tolist()
    # Pythonify the Numpy and PyTorch
    if isinstance(inmat,(torch.Tensor,np.ndarray)):
        mat = inmat.tolist()
    return mat

def sm_md(inmat):
    md = ""
    md += "\\begin{bmatrix}"
    tmp_rows = list()
    mat = to_list(inmat)
    for rr in range(len(mat)):
        tmp_rows.append(" & ".join([(f'{item:.2f}').rstrip('0').rstrip('.') for item in mat[rr]]))
    md += "\\\\".join(tmp_rows)
    md += "\\end{bmatrix}"
    return display(Markdown(md))

# from IPython.display import Latex

def sm(inmat,mname="A"):
    latex = ""
    latex += "\\renewcommand{\\vec}[1]{\\boldsymbol{#1}}\n"
    latex += "\\renewcommand{\\matrix}[1]{\\boldsymbol{\\mathrm{#1}}}\n"
    latex += "\\newcommand{\\tensor}[1]{\\boldsymbol{\mathrm{#1}}}\n"
    latex += "\\boldsymbol{\\mathrm{"+mname+"}}"
    latex += " = \\begin{bmatrix}"
    mat = to_list(inmat)
    tmp_rows = list()
    for rr in range(len(mat)):
        tmp_rows.append(" & ".join([(f'{item:.2f}').rstrip('0').rstrip('.') for item in mat[rr]]))
    latex += "\\\\".join(tmp_rows)
    latex += "\\end{bmatrix}"
    return display(Math(latex))

# call as sm([[1,2,3],[4,5,6]],mname="V")

## Define the reference matrices to be used later

* simple python nested lists
* pythorch matrix made of that plain python
* tensorflow matrix made the same way as the pytorch

In [3]:
py_matrix = [[1,2,3],[4,5,6]]
np_matrix = np.matrix(py_matrix)
tf_matrix = tf.constant(py_matrix,dtype=float)
pytorch_matrix = torch.tensor(py_matrix)

2021-10-20 10:46:53.542989: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
py_matrix

[[1, 2, 3], [4, 5, 6]]

In [5]:
np_matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
tf_matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
pytorch_matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

## Improve the display

In [8]:
sm(py_matrix,mname="V")

<IPython.core.display.Math object>

In [9]:
sm(tf_matrix)

<IPython.core.display.Math object>

In [10]:
sm(np_matrix)

<IPython.core.display.Math object>

In [11]:
sm(tf_matrix)

<IPython.core.display.Math object>

In [12]:
sm_md(tf_matrix)

\begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\end{bmatrix}

## How is it done ?

The essential functions are `sm` and `sm_md` where the `sm` uses **Latex** rendering while the `sm_md` is using the **Markdown**.